import NavierStokes.ComparatorSolution
import Euler.Solution

#check NavierStokes.Comparator.navier_stokes_breakdown_R3
#check NavierStokes.Comparator.navier_stokes_breakdown_periodic
#check Euler.euler_breakdown_R3
#check Euler.exists_compact_smooth_euler_singularity

#print axioms NavierStokes.Comparator.navier_stokes_breakdown_R3
#print axioms NavierStokes.Comparator.navier_stokes_breakdown_periodic
#print axioms Euler.euler_breakdown_R3
#print axioms Euler.exists_compact_smooth_euler_singularity
